services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb-tekbetter
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  redis:
    image: redis:latest
    container_name: redis-tekbetter
    environment:
      REDIS_PASSWORD: azerty
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

volumes:
  dbdata6: